# Generated by Django 2.0.7 on 2019-02-06 14:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('attendance_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=20)),
                ('marks', models.IntegerField(default=10)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=1)),
                ('parent_name', models.CharField(max_length=201)),
                ('address', models.TextField(max_length=400)),
                ('phone_no', models.IntegerField(default=10, unique=True)),
                ('department', models.CharField(max_length=30)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(default=10, unique=True)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Course')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='roll_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.Course'),
        ),
    ]
